FROM apache/airflow
RUN pip install psycopg2-binary==2.9.1
RUN pip install pandas==1.1.0
RUN pip install python-decouple==3.5
RUN pip install requests==2.26.0
RUN pip install apache-airflow-providers-postgres==4.0.0
RUN pip install matplotlib==3.5.1
RUN pip install SQLAlchemy==1.3.18
RUN pip install aiobotocore==2.1.2
RUN pip install boto3==1.20.0
RUN pip install fsspec==2022.2.0
RUN pip install s3fs==2022.2.0
RUN pip install apache-airflow-providers-amazon==3.2.0
RUN pip install sagemaker==1.72.1
